---
dist: .artifacts/goreleaser
# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
env:
  - SLACK_CHANNEL={{ if index .Env "SLACK_CHANNEL" }}{{ .Env.SLACK_CHANNEL }}{{else}}''{{end}}''
  - SLACK_WEBHOOK={{ if index .Env "SLACK_WEBHOOK" }}{{ .Env.SLACK_WEBHOOK }}{{else}}''{{end}}''
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
    - tfplugindocs generate --tf-version 1.2.8 --examples-dir examples # move this to mage later, since it is slow
builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - --batch
      - --local-user
      - '{{ .Env.GPG_FINGERPRINT }}' # set this environment variable for your signing key
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}
release:
  # If you want to manually examine the release before its live, uncomment this line:
  draft: false
  replace_existing_draft: true
  skip_upload: false
announce:
  slack:
    enabled: true
    # The name of the channel that the user selected as a destination for webhook messages.
    channel: '{{ .Env.SLACK_CHANNEL }}'
    message_template: ':terraform: {{ .ProjectName }} {{ .Tag }} is out! Terraform Registry: https://registry.terraform.io/providers/DelineaXPM/dsv/{{ trimprefix .Tag "v" }} GitHub release: {{ .ReleaseURL }}'
    # Emoji to use as the icon for this message. Overrides icon_url.
    icon_emoji: ':tada:'
sboms:
  - artifacts: archive
    documents:
      - '${artifact}.spdx.sbom'
changelog:
  skip: false
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'CI & Chore'
      regexp: "^.*(fix|chore|build)[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^style:'
