---
name: lint
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
permissions:
  pull-requests: write
  checks: write
  contents: read
jobs:
  lint:
    uses: delineaxpm/github-workflows/.github/workflows/lint.yml@main
    secrets: inherit
